os:
  - linux

arch: arm64

sudo: required

python:
  - "3.8"

dist: bionic

language: python

services:
  - docker

install:
  - python --version
  - pip install pip -U
  - pip install --no-binary cryptography
  - pip install -r requirements.txt
  - pip install .
  - pwd
  - cmsd --setup
  - cmsd help

script:
  - pytest -v --capture=no tests
