dist: bionic

sudo: required

language: python

python:
  - "3.8"

services:
  - docker

install:
  - python --version
  - pwd
  - pip install -r requirements.txt
  - pip install .
  - cmsd --setup
  - cmsd help

script:
  - pytest -v --capture=no tests
